### ISSUE TITLE
Safari 6.0.5 [Mac] handle sometimes jumps to the left

### ISSUE THREAD

**Issue by ondrejrohon** [zurb/twentytwenty#1]
Hi guys,

firstly, thank you for your hard work and beautiful plugin. 
But I found an issue today. On mac, safari 6.0.5 while sliding, the handle sometimes suddenly jumps to the left. And therefore it will show "Before" picture completely. After moving it a bit more it jumps back to the intended position.
Issue can be reconstructed even on plugin home page.

http://zurb.com/playground/twentytwenty

Thanks for fixing it, I would love to use it on my latest project.

Johnny

**Comment by Winterhart** [comment]
Hi guys,

I am having a problem with the twenty twenty plugin on safari only.
If <meta name="apple-mobile-web-app-capable" content="yes">
and my status bar is in "hide mode" I can't see the plugin
and if my status bar is in "show mode" I can see the plugin

On another hand, if the <meta name="apple-mobile-web-app-capable" content="no">
and my status bar is in "hide mode" I can see the plugin
and my status bar is in "show mode" I can't see the plugin

Is it possible to remove the "link" between the status bar and the plugin of the status bar?

Thanks
