### ISSUE TITLE
Is it responsive?

### ISSUE THREAD

**Issue by ghost** [zurb/twentytwenty#15]
Hi,

Great work on the plugin.

I re-read your description few times, and it looks like this implementation should be responsive. But this is not the case?

In my scenario, I used width 100% on wrapper, but image never gets enlarged or resized down. I see in css height is fixed.

What would you suggest to do in this situation?

**Comment by rflx** [comment]
Hi mhayes – nice pluginm thank you for this one!
Just came across with this responsive issue. If I use the plugin out of the box, the image will scale when i'm resizing the browser window but it will be stretched due of a fixed height value in the `twentytwenty-container` element.

> There is a window resize event already in place that adjusts the container height (letting css control the image width)

I don't know, but should there be used `height: auto;` to scale the `img` height according to the width?

Would appreciate to hear from you,
thanks and cheers!
