### ISSUE TITLE
Not support for rails-assets

### ISSUE THREAD

**Issue by msyesyan** [zurb/twentytwenty#23]
I used to use rails-assets gem to build my projects, just like rails-assets-bootstrap,so can you tag your repository so I can add it to the rails-assets components lists?You can find rails-assets here:"https://rails-assets.org/components"

**Comment by raphaeleidus** [comment]
closing as a duplicate of https://github.com/zurb/twentytwenty/issues/20

rails-assets runs on bower. Once we support bower, rails-assets will start working too.
