### ISSUE TITLE
Does not work on Rails

### ISSUE THREAD

**Issue by dahliacreative** [zurb/twentytwenty#25]
I've implemented on a rails project and it simply does not work, height of the container is just set to 0px.
Is there a fix for this or can anyone recommend a similar plugin which is rails friendly?

**Comment by srussking** [comment]
I am definitely using this on Rails and it is working fine, this is pretty much pure JS and SASS though so it should run on just about any framework.

Assuming you are loading the js and css fine, you may want to ensure that the images are loaded before initting it. I use imagesLoaded (https://github.com/desandro/imagesloaded) running as such:

$('.image_container').imagesLoaded(function(){
   $('.image_container').twentytwenty();
});

**Comment by raphaeleidus** [comment]
@dahliacreative I am going to close this for now, if this is still an issue for you please reopen and if possible provide a link to the page where it is breaking or the sample output html. 

I believe you may have a problem where you are not loading the javascript or css correctly

**Comment by dahliacreative** [comment]
This was so long ago, I don't even remember what project it was. I think I ended up building my own.
