### ISSUE TITLE
Is it possible to edit the text "Before" and "After"

### ISSUE THREAD

**Issue by lisaevolve** [zurb/twentytwenty#28]
Hi there,

Is it possible to edit the text "Before" and "After"?

Lisa

**Comment by francesco14** [comment]
Is it possible to get custom before and after labels dinamically without using css? Maybe using a title attribute on the img tag?

**Comment by francesco14** [comment]
I just made a PR to manage the before and after label by the title attributes on the images. No more need to change them by CSS. #59 .

I hope it helps someone.
Bye

**Comment by raphaeleidus** [comment]
this is now implemented
```javascript
$(".twentytwenty-container").twentytwenty({
  before_label: 'January 2017', // Set a custom before label
  after_label: 'March 2017' // Set a custom after label
});
```
