### ISSUE TITLE
Is it possible to switch the slider from horizontal to vertical?

### ISSUE THREAD

**Issue by nogginfuel** [zurb/twentytwenty#29]
I have a use case where I would like the diff slider to move vertically (top/bottom) instead of side to side. Which variables need switched to make that function a possibility?

**Comment by brettdewoody** [comment]
Yes, there is an attribute for this. 

Add ` data-orientation="vertical"` to the `twentytwentycontainer`, so your code looks something like:

    <div class="twentytwenty-container" data-orientation="vertical">
      <img src="img/1_1.jpg" />
      <img src="img/1_2.jpg" />
    </div>

**Comment by nogginfuel** [comment]
@brettdewoody I appreciate you taking the time to answer this. I did give that a try but it did not seem to change the orientation of the slider for me. Is there a code pen or example where I could see it working to compare to see if my code is hung up on something? Any additional help is greatly appreciated.

**Comment by brettdewoody** [comment]
If you download the TwentyTwenty zip file you'll see an example in `index.html` of the vertical slider.

**Comment by nogginfuel** [comment]
Thanks for the help @brettdewoody . I'm not sure what is causing my version not to work. I do see it working in the `index.html` as you mentioned. The version I had been working from may have been prior to them adding the vertical example. I guess I just need to keep my build more up to date.

**Comment by oompt** [comment]
You don't add an(y) attribute to the container. You register the option when you make the function call. 

![img](http://f.cl.ly/items/0e2r3420031L2K1X2k2E/Image%202015-09-28%20at%201.29.27%20PM.png)
