### ISSUE TITLE
Initial slider position bug

### ISSUE THREAD

**Issue by digitalclover** [zurb/twentytwenty#43]
I've created a page that has seven containers, each with their own image comparison module.  I've initialized the plugin using a class name, however I'm getting very inconsistent performance about where the slider is positioned on the initial load.

Sometimes the slider starts at the default center position, but other times it will start all the way to the left.  There isn't any pattern to the bug since multiple page refreshes always yield different results.

Is there a better, or more efficient way to load multiple sliders without having this bug appear?

**Comment by raphaeleidus** [comment]
@digitalclover do you have a sample page where I could see this issue occuring?

**Comment by digitalclover** [comment]
@raphaeleidus I ended up using another resource for this functionality. I'll close this since I don't have a way to pursue this issue any further.
