### ISSUE TITLE
'Before' Image offset doesn't show at startup

### ISSUE THREAD

**Issue by Acoleno** [zurb/twentytwenty#48]
Hi Folks

I got an issue I just experienced on the website I'm working on. I'm using Twentytwenty with an offset set at 0.2. When the twentytwenty container is shown, I can only see the second image ('After' in default configuration, 'Before' on mine but whatever) while the handle is correctly set à 20% of the width. (Screenshot)

Whenever I click on or drag the handle, everything goes back to normal and the plugin works.

Any ideas ?
Thanks
![sans-titre-1](https://cloud.githubusercontent.com/assets/17296603/13113716/92a0c1e0-d590-11e5-86e6-e41d106995cf.jpg)

**Comment by mhayes** [comment]
My initial thoughts are maybe there's an issue with how TwentyTwenty is being initialized, can you confirm it's on the `$(window).load()` event?

Also posting a link to your code would be very helpful, thanks @Acoleno!

**Comment by Acoleno** [comment]
Hey @mhayes! Thanks for your time

Bascially, it was into `$(document).ready()` event so I did move it into `$(window).load()` but as you can guess, it didn't solve the problem.

I'm working on an automatically generated wall gallery . 
As you can deduce from the screenshot, each before/after image is wrapped into a fancybox.

Here's the HTML part:

```HTML
<div class="fancybox-wrapper">
	<div class="fancybox-wrapper-target"  id="matte-painting-<?php the_ID();?>">
		<div class="fancybox-matte-painting twentytwenty" style="width:<?php echo  $after_image['width'].'px';?>; min-height: <?php echo $after_image['height'].'px';?>">
			<img src="<?php echo $after_image['url'];?>" width="<?php echo $after_image['width'];?>" height="<?php echo $after_image['height'];?>"/>
			<img src="<?php echo $before_image['url'];?>" width="<?php echo $before_image['width'];?>" height="<?php echo $before_image['height'];?>"/>	
		</div>
	</div>
</div>
```

And the related js:
```javascript
$(window).load(function (){
		$("a.fancybox-matte-painting-link").each(function (){
	    	var target = $('div#matte-painting-'+ $(this).attr('data-fancybox-href'));
			$(this).fancybox({
	        'href'   : '#'+target.attr('id'),
	   		});
		});
		$('div.fancybox-matte-painting').each(function() {
			$(this).twentytwenty();	
		});
	});
```
There's no specific css except some minor width & height ajustements.

Ask me if you need more information!

**Comment by mhayes** [comment]
I thought that it might have something to do with manually setting the image dimensions on the Fancybox container but that doesn't seem to be the case. I put together an example that showcases Fancybox and TwentyTwenty working together. Here's the example page:

http://mhayes.github.io/example-twentytwenty-fancybox/

The corresponding code I used was not radically different from what you were using. It can be found here:
https://github.com/mhayes/example-twentytwenty-fancybox/blob/master/index.html

The biggest different could be that you can have to trigger a window resize event when the Fancybox opens as that will adjust dimensions on the slider. Take a peek at the `atterLoad` event in the code I mentioned above.

If you're still running into issues it would be useful to see the full site you're working on. If you posted a link to your development/staging environment that would be helpful.

Hope that helps you out, cheers!

**Comment by Acoleno** [comment]
I just integrated the `afterload` event, but it didn't made the trick. 
I'm glad to see I didn't go into weird direction when it came to combine fancybox & twentytwenty functionnality. The issue shouldn't be so far. 

I made the test with both jquery versions 1.12 and 2.2 and tried to deactivate other jquery plugins I installed. The issue is still there.

You can check this out on [the staging environment (portfolio -> matte Painting)](http://dev.pascalcasolari.com/portfolio/matte-painting/)
The call is located at the bottom of `funcion.js` file.

Still really grateful for your time.

**Comment by mhayes** [comment]
Hey @Acoleno I took a look at the `functions.js` file and it looks like if you add a `setTimeout` function on the after load event it will work as expected. It feels like there should be a more elegant solution than this, but it does appear to work in my browser. Here's the relevant code to try:

```js
$("a.fancybox-matte-painting-link").each(function (){
  var target = $('div#matte-painting-'+ $(this).attr('data-fancybox-href'));
  $(this).fancybox({
      'href'   : '#'+target.attr('id'),
      afterLoad: function () {
        // Adding the the timeout 
        setTimeout(function() {
            $(window).trigger("resize");
        }, 100);
      }
    });
});
```

I also noticed that the `functions.js` is being included before the other plugins (`jquery.event.move.js` and `jquery.twentytwenty.js`). It doesn't appear to be causing any issues, but I believe the order should be:

```html
<script type='text/javascript' src='http://dev.pascalcasolari.com/wp-content/themes/pascalCasolariStudio/js/jquery.event.move.js'></script>
<script type='text/javascript' src='http://dev.pascalcasolari.com/wp-content/themes/pascalCasolariStudio/js/jquery.fancybox.pack.js'></script>
<script type='text/javascript' src='http://dev.pascalcasolari.com/wp-content/themes/pascalCasolariStudio/js/jquery.mixitup.js'></script>
<script type='text/javascript' src='http://dev.pascalcasolari.com/wp-content/themes/pascalCasolariStudio/js/jquery.hoverdir.js'></script>
<script type='text/javascript' src='http://dev.pascalcasolari.com/wp-content/themes/pascalCasolariStudio/js/jquery.twentytwenty.js'></script>
<script type='text/javascript' src='http://dev.pascalcasolari.com/wp-includes/js/wp-embed.min.js?ver=4.4.2'></script>
<!-- moved this to the bottom -->
<script type='text/javascript' src='http://dev.pascalcasolari.com/wp-content/themes/pascalCasolariStudio/js/functions.js?ver=20150825'></script>
```

**Comment by Acoleno** [comment]
Hey @mhayes.

This totally made the trick !
I'll take a look at your other advices.

We can call this one solved. Thanks again.

**Comment by mhayes** [comment]
You're welcome, glad it worked @Acoleno :)
