### ISSUE TITLE
Slow drag

### ISSUE THREAD

**Issue by jonathandion** [zurb/twentytwenty#52]
Hey,

I'm having a issue, when I drag the slider it's super slow compare to the demo. I tried the plugin on a separated project it's working fine. I don't know why I'm having this problem. I'm using jQuery 1.10.1 like the demo and also event.move.js.

Any thought ?

Thanks.

**Comment by mhayes** [comment]
@jonathandion the only thing I can think of would be that there's some other code running in your project that is slowing things down. Perhaps there are too many events bound to the window `resize` event.

Would you mind post a link to your site and/or source code? Thanks!

**Comment by jonathandion** [comment]
Hey @mhayes thanks I solved the problem. I checked all the events. Nothing.  Somebody before me added 

```css
* {
    -webkit-transition: all .3s ease;
    transition: all .3s ease;
}
```

:sob: 

Thanks.
