### ISSUE TITLE
TinyMCE Implementation

### ISSUE THREAD

**Issue by skazhikadyadya** [zurb/twentytwenty#65]
Hi, thank you for nice plugin. 

I have a two question: 

1. Is that plugin compatible with Bootstrap 3.x?
2. How about TinyMCE button for insert TwentyTwenty block into editor?

Thank you.

**Comment by raphaeleidus** [comment]
1. I believe so but I haven't tested it myself
2. That is an interesting idea, would you be up for creating a TinyMCE extension?
