### ISSUE TITLE
Vertical Slider issue on IOS devices

### ISSUE THREAD

**Issue by munirkamal** [zurb/twentytwenty#68]
The vertical slider doesn't works well in IOS devices. When we touch and scroll it actually scrolls the page and not the slider. 

Please let me know if there is a fix for that?

Thanks,
Munir

**Comment by lucash** [comment]
I have got the same issue. I found out that attaching any touchmove event handler (even an empty one) to `slider` (within jquery.twentytwenty.js) solves the issue. However I was not yet able to find out why this is the case, would assume a bug in jquery.event.move.

`slider.on("touchmove", function(event) {});`
