### ISSUE TITLE
not working with jQuery 2.1.1

### ISSUE THREAD

**Issue by sonstiges** [zurb/twentytwenty#81]
Hi,
I love your plugin twentytwenty and we are using it for showing the reconstruction of a german castle in an app. It is still in developing. Now there is the problem, that we have to upgrade to jQuery 2.1.1. 
Twentytwenty is not working with jQuery 2.1.1. and I don´t get any message in the debug tool, so I don´t know where to search for the issue. 
Do you have an idea what could be the problem between twentytwenty and jQuery 2.1.1?

Thanks for taking time for us.

**Comment by raphaeleidus** [comment]
the version of `jquery.event.move.js` that we use is for jquery 3.
You will need to find an older version of event.move and include that
