### ISSUE TITLE
How i add this to my site ?

### ISSUE THREAD

**Issue by BlackB1RDD** [zurb/twentytwenty#83]
i have a wix site and i want to add this before and after slider to my site. how i do its ?
or if someone can send me the complete html code for this slider its will be very helpful (i can make custom html box in wix so i can enter the code inside ths box and its give me the slider)
Have A Good Day :)

**Comment by raphaeleidus** [comment]
hi @BlackB1RDD 
in the custom html form put this code after replacing the two image urls with your images.
```html
<div id="container1">
 <!-- The before image is first -->
 <img src="http://placehold.it/800x500&amp;text=1" />
 <!-- The after image is last -->
 <img src="http://placehold.it/800x500&amp;text=2" />
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.rawgit.com/zurb/twentytwenty/599bc2df/js/jquery.event.move.js"></script>
<script src="https://cdn.rawgit.com/zurb/twentytwenty/599bc2df/js/jquery.twentytwenty.js"></script>
<link rel="stylesheet" href="https://cdn.rawgit.com/zurb/twentytwenty/599bc2df/css/twentytwenty.css" type="text/css" media="screen" />

<script>
$(function(){
  $("#container1").twentytwenty();
});
</script>
```

**Comment by brymonster** [comment]
Hello there! resurrecting this one!
Any reason why my HTML frame using this code never loads first try?
Always have to reload the website.. is there a better way?
thanks!

**Comment by murfstar0007** [comment]
> Hello there! resurrecting this one!
> Any reason why my HTML frame using this code never loads first try?
> Always have to reload the website.. is there a better way?
> thanks!

Hi Brymonster,

try this script:
<script>
	$(document).ready(function() {
		$(".twentytwenty-container").each(function(){
			$(this).twentytwenty().trigger('resize');
		});
	});
	$(window).load(function() {
        $(window).trigger("resize.twentytwenty");
    });
</script>

**Comment by brymonster** [comment]
@murfstar0007 thanks for the reply! 
unfortunately I don't understand what you are suggesting. 
here is my current use. how would I modify it?

```
<div id="container1">
 <!-- The before image is first -->
 <img src="https://static.wixstatic.com/media/38adcd_20cbaf4d121c4b1cac6381fc5b714d8c~mv2.jpg" />
 <!-- The after image is last -->
 <img src="https://static.wixstatic.com/media/38adcd_47920328a4d0402bb62a24f5250018b6~mv2.jpg" />
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.rawgit.com/zurb/twentytwenty/599bc2df/js/jquery.event.move.js"></script>
<script src="https://cdn.rawgit.com/zurb/twentytwenty/599bc2df/js/jquery.twentytwenty.js"></script>
<link rel="stylesheet" href="https://cdn.rawgit.com/zurb/twentytwenty/599bc2df/css/twentytwenty.css" type="text/css" media="screen" />

<script>
$(function(){
  $("#container1").twentytwenty();
});

> </script>
```

**Comment by murfstar0007** [comment]
@brymonster, try replacing 
```
<script>
$(function(){
  $("#container1").twentytwenty();
});

> </script>
```


and change it to 

```
<script>
$(document).ready(function() {
	$("#container1").each(function(){
		$(this).twentytwenty().trigger('resize');
	});
});
$(window).load(function() {
       $(window).trigger("resize.twentytwenty");
});
</script>
```

hopefully that works on wix.  it works on my sites that i build (but they not on wix).

**Comment by brymonster** [comment]
Thanks @murfstar0007 that may have done the trick, combined with much smaller image sizes. any way to change the **font**? using the above code Im getting serif in on an entirely sans serif webpage. looks like the foundation.css is using Helvetica, but thats not what my slide is showing up.. 
would love to change it. thanks!

<img width="308" alt="Screen Shot 2020-04-05 at 4 48 17 PM" src="https://user-images.githubusercontent.com/12586478/78509639-75c91e00-775d-11ea-8d09-3fa42ec209bc.png">

**Comment by murfstar0007** [comment]
if you can move the css in the html 
```<link rel="stylesheet" href="https://cdn.rawgit.com/zurb/twentytwenty/599bc2df/css/twentytwenty.css" type="text/css" media="screen" />```
above your main fonts/style css file. 

if you can not do this. find the class's you want to override in the HTML then create a css rule in your CSS file, if that still doesnt work add !important; next to each style in your css file. this will override the imported styles from twentytwenty.css
