### ISSUE TITLE
How best to ensure entire image is always visible?

### ISSUE THREAD

**Issue by lokoyan** [zurb/twentytwenty#88]
Hello, first, thank you for developing such a great tool.  I'm not a programmer, and this was so easy to implement.

I'm hoping to set it up so that my entire image is visible on the screen (horizontally AND vertically).  Using the "large-12" class in the outer <div> it uses (almost) all the width, but the image is too tall, so extends off the bottom of the screen.  Any suggestions on the best way to have it fit so the entire image is showing?

Thanks!

**Comment by raphaeleidus** [comment]
with CSS you can set the image to have a `max-height: 100vh` and `max-width: 100vw` this will work for all modern browsers for some older it wont constrain it but it wont break it either.
